name = "frontend"
version = "1.0.0"
target = "javascript"
description = "Roxy UI on Lustre"


[dependencies]
gleam_stdlib = ">= 1.0.0 and < 2.0.0"
lustre = ">= 5.7.1 and < 6.0.0"

gleam_json = ">= 3.1.0 and < 4.0.0"
gleam_http = ">= 4.4.0 and < 5.0.0"
shared = { path = "../shared" }

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
lustre_dev_tools = ">= 2.3.6 and < 3.0.0"

[tools.lustre.bin]
bun = "system"

[tools.lustre.dev]
host = "0.0.0.0"
port = 1234
watch = ["../shared/src"]
proxy = { from = "/api", to = "http://backend:8080/api" }

[tools.lustre.build]
outdir = "dist"
minify = true

[tools.lustre.html]
title = "Roxy"
stylesheets = [
  { href = "/ui/styles/reset.css" },
  { href = "/ui/styles/tokens.css" },
  { href = "/ui/styles/theme.css" },
  { href = "/ui/styles/globals.css" },
]
